#' Load Credit Card Name Data
#'
#' This function returns a character, or factor, vector of examples names that might appear on credit cards.
#' @param limit Provide the maximum number of records to return.  Defaults to NA, or all available records.
#' @param ... zzz
#' @keywords demo example data
#' @export
#' @examples
#' x <- get.demo.data
#'
#' x <- get.demo.data(10)
get.demo.data <- function(limit = NA, ...) {

  names <- read.table(header = FALSE, sep = "|", stringsAsFactors = FALSE,text = "
CASIO MARY JOY C
KELLY  NICHOLAS A
KELLY  NICHOLAS C
KELLY  NICHOLAS L
KELLY  NICHOLAS M
KELLY IV NICHOLAS J
KELLY NICHOLAS  M
KELLY NICHOLAS A
KELLY NICHOLAS ALEX
KELLY NICHOLAS ANDR
KELLY NICHOLAS B
KELLY NICHOLAS C
KELLY NICHOLAS CHAS
KELLY NICHOLAS COLE
KELLY NICHOLAS D
KELLY NICHOLAS E
KELLY NICHOLAS EDWA
KELLY NICHOLAS F
KELLY NICHOLAS G
KELLY NICHOLAS J
KELLY NICHOLAS JOSE
KELLY NICHOLAS K
KELLY NICHOLAS L
KELLY NICHOLAS M
KELLY NICHOLAS P
KELLY NICHOLAS R
KELLY NICHOLAS RASH
KELLY NICHOLAS ROBE
KELLY NICHOLAS S
KELLY NICHOLAS SIMO
KELLY NICHOLAS T
KELLY NICHOLAS W
KELLY NICK A
KELLY NICK F
KELLY NICK M
KELLY NICK MELVIN
KELLY NICK R
KELLY NICK T
NICHOLAS  KELLY
NICHOLAS A KELLY
NICHOLAS J KELLY
NICHOLAS KELLY
NICHOLAS KELLY A
NICHOLAS KELLY ANNE
NICHOLAS KELLY C
NICHOLAS KELLY D
NICHOLAS KELLY E
NICHOLAS KELLY H
NICHOLAS KELLY J
NICHOLAS KELLY L
NICHOLAS KELLY M
NICHOLAS KELLY MC
NICHOLAS KELLY R
NICHOLAS KELLY THOM
NICHOLAS KELLY W
NICHOLAS L KELLY
NICHOLAS M KELLY
NICHOLAS R KELLY
NICHOLAS S KELLY
NICHOLAS S KELLYNIC
NICK MRS KELLY G")

  names <- names[,1]

}
